services:
  backend:
    build: ./backend
    container_name: tic-tac-toe-backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    working_dir: /app
    command: go run cmd/main.go
    networks:
      - tic-tac-toe-net

  frontend:
    build: ./frontend
    container_name: tic-tac-toe-frontend
    ports:
      - "19000:19000"  # For Metro bundler
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: npm run start
    networks:
      - tic-tac-toe-net

networks:
  tic-tac-toe-net:
    driver: bridge
