# Use postgres/example user/password credentials
services:
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    
    volumes:
      - ./postgres/data:/data/postgres/data
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
      PGDATA: /data/postgres/data
    ports:
      - 5432:5432

  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - 8080:8080

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379

  # backend:
  #   depends_on:
  #     - db
  #     - redis
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   environment:
  #     - SECRET=ASDF
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./backend/config.yml:/app/config.yml
  #     - ./backend/logs:/app/logs
  #   command: ["/app/server"]

  prometheus:
    image: prom/prometheus
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus